### ISSUE TITLE
Add support for extensions

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis-integration-runtime#21]
There should be new kind "extension" used to attach processors to a route:

```yaml
- kind: "extension"
    name: "com.github.lburgazzoli.application.extension.beans.MyStep"
    properties:
      something: "ThisIsSomething"
      key1: "val1"
      key2: "val2"
```
The "extension" class should implement the following interface:

```java
@FunctionalInterface
public interface SyndesisStepExtension {
    ProcessorDefinition configure(CamelContext context, ProcessorDefinition definition, Map<String, Object> parameters);
}
```
