### ISSUE TITLE
Support Hystrix EIP

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis-integration-runtime#26]
Flow should looks like:

```yaml
---
flows:
- steps:
  - kind: "endpoint"
    uri: "direct:start"
  - kind: "hystrix"
    steps:
    - kind: "endpoint"
      uri: "..."
    onFallback:
      kind: "endpoint"
      uri: "..."
```

There should eventually be a global option in syndesis-ui to configure hystrix options. The `hystrix` step should have a subset of configuration options.
